package report

import (
	"fmt"
	"strings"

	"github.com/arinorr/prism/internal/agents"
)

// Markdown generates a markdown report from the review data.
func Markdown(d *Data) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Prism Review: PR #%s\n\n", d.PR.Number)
	fmt.Fprintf(&b, "**%s**\n\n", d.PR.Title)

	// Health score header.
	if d.Result.HealthScore.Score > 0 || d.Result.HealthScore.Grade != "" {
		fmt.Fprintf(&b, "## Health Score: %s (%s) — %s\n\n",
			d.Result.HealthScore.Description, d.Result.HealthScore.Grade, d.Result.HealthScore.Verdict)
	}

	fmt.Fprintf(&b, "Files changed: %d | Agents: %s", len(d.PR.Files), strings.Join(d.Roles, ", "))
	if d.Duration != "" {
		fmt.Fprintf(&b, " | Duration: %s", d.Duration)
	}
	b.WriteString("\n\n---\n\n")

	// Failed agents notice.
	if len(d.Result.FailedAgents) > 0 {
		fmt.Fprintf(&b, "> ⚠️ **%d agent(s) failed:** %s\n\n",
			len(d.Result.FailedAgents), strings.Join(d.Result.FailedAgents, ", "))
	}

	b.WriteString("## Summary\n\n")
	b.WriteString(d.Result.Summary)
	b.WriteString("\n\n")

	// Findings grouped by scope, then by file — use deduped if available.
	if len(d.Result.DedupedFindings) > 0 {
		byScope := groupDedupedByScope(d.Result.DedupedFindings)
		for _, section := range byScope {
			fmt.Fprintf(&b, "---\n\n## %s\n\n", section.title)
			for _, group := range section.groups {
				fmt.Fprintf(&b, "### `%s`\n\n", group.file)
				b.WriteString("| Line | Risk | Category | Votes | Summary |\n")
				b.WriteString("|------|----------|----------|-------|---------|\n")
				for i := range group.findings {
					f := &group.findings[i]
					line := "-"
					if f.Line > 0 {
						line = fmt.Sprintf("%d", f.Line)
					}
					votes := fmt.Sprintf("%d/%d (%.0f%%)", f.VoteCount, f.TotalAgents, f.Consensus()*100)
					fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n",
						line, severityBadge(f.Risk), f.Category, votes, f.Summary)
				}
				b.WriteString("\n")

				// Details for warnings and criticals.
				for i := range group.findings {
					f := &group.findings[i]
					if f.Risk == severityInfo {
						continue
					}
					voters := strings.Join(f.Voters, ", ")
					consensus := fmt.Sprintf("%.0f%%", f.Consensus()*100)
					if f.Line > 0 {
						fmt.Fprintf(&b, "**%s** (line %d, consensus: %s, %d/%d agents: %s) — %s\n\n",
							severityBadge(f.Risk), f.Line, consensus, f.VoteCount, f.TotalAgents, voters, f.Summary)
					} else {
						fmt.Fprintf(&b, "**%s** (consensus: %s, %d/%d agents: %s) — %s\n\n",
							severityBadge(f.Risk), consensus, f.VoteCount, f.TotalAgents, voters, f.Summary)
					}
					b.WriteString(f.Detail)
					b.WriteString("\n\n")
					if f.CodeExample != "" {
						b.WriteString("```\n")
						b.WriteString(f.CodeExample)
						b.WriteString("\n```\n\n")
					}
				}
			}
		}
	} else if len(d.Result.Findings) > 0 {
		byScope := groupRawByScope(d.Result.Findings)
		for _, section := range byScope {
			fmt.Fprintf(&b, "---\n\n## %s\n\n", section.title)
			for _, group := range section.groups {
				fmt.Fprintf(&b, "### `%s`\n\n", group.file)
				b.WriteString("| Line | Risk | Category | Agent | Summary |\n")
				b.WriteString("|------|----------|----------|-------|---------|\n")
				for i := range group.findings {
					f := &group.findings[i]
					line := "-"
					if f.Line > 0 {
						line = fmt.Sprintf("%d", f.Line)
					}
					fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n",
						line, severityBadge(f.Risk), f.Category, f.Role, f.Summary)
				}
				b.WriteString("\n")

				for i := range group.findings {
					f := &group.findings[i]
					if f.Risk == severityInfo {
						continue
					}
					if f.Line > 0 {
						fmt.Fprintf(&b, "**%s** (line %d, %s) — %s\n\n",
							severityBadge(f.Risk), f.Line, f.Role, f.Summary)
					} else {
						fmt.Fprintf(&b, "**%s** (%s) — %s\n\n",
							severityBadge(f.Risk), f.Role, f.Summary)
					}
					b.WriteString(f.Detail)
					b.WriteString("\n\n")
					if f.CodeExample != "" {
						b.WriteString("```\n")
						b.WriteString(f.CodeExample)
						b.WriteString("\n```\n\n")
					}
				}
			}
		}
	}

	if len(d.Result.Suggestions) > 0 {
		fmt.Fprintf(&b, "---\n\n*%d inline suggestions available. Use `--comment` to post them to the PR.*\n\n", len(d.Result.Suggestions))
	}

	// Usage summary.
	if d.Usage.TotalTokens() > 0 {
		totalInput := d.Usage.TotalInputTokens()
		fmt.Fprintf(&b, "---\n\n**Review stats:** %dk input + %dk output = %dk tokens | $%.2f",
			totalInput/1000, d.Usage.OutputTokens/1000, (totalInput+d.Usage.OutputTokens)/1000, d.Usage.CostUSD)
		if d.Duration != "" {
			fmt.Fprintf(&b, " | %s", d.Duration)
		}
		b.WriteString("\n\n")
	}

	b.WriteString("---\n\n*Generated by [Prism](https://github.com/arinorr/prism)*\n")

	return b.String()
}

func severityBadge(s agents.Risk) string {
	switch s {
	case severityCritical:
		return "🔴 critical"
	case severityWarning:
		return "🟡 warning"
	default:
		return "🔵 info"
	}
}
