// Package report generates review reports in markdown, HTML, and JSON formats.
package report

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/yuin/goldmark"

	"github.com/arinorr/shinobi/internal/agents"
	"github.com/arinorr/shinobi/internal/gh"
)

// Data holds everything needed to generate a report.
type Data struct {
	PR       *gh.PR
	Result   *agents.ReviewResult
	Roles    []string
	Duration string
}

// Markdown generates a markdown report from the review data.
func Markdown(d *Data) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Shinobi Review: PR #%s\n\n", d.PR.Number)
	fmt.Fprintf(&b, "**%s**\n\n", d.PR.Title)
	fmt.Fprintf(&b, "Files changed: %d | Agents: %s", len(d.PR.Files), strings.Join(d.Roles, ", "))
	if d.Duration != "" {
		fmt.Fprintf(&b, " | Duration: %s", d.Duration)
	}
	b.WriteString("\n\n---\n\n")

	// Summary from synthesis.
	b.WriteString("## Summary\n\n")
	b.WriteString(d.Result.Summary)
	b.WriteString("\n\n")

	// Findings grouped by file.
	if len(d.Result.Findings) > 0 {
		b.WriteString("---\n\n## Findings by File\n\n")
		grouped := groupByFile(d.Result.Findings)
		for _, group := range grouped {
			fmt.Fprintf(&b, "### `%s`\n\n", group.file)
			b.WriteString("| Line | Severity | Agent | Summary |\n")
			b.WriteString("|------|----------|-------|---------|\n")
			for _, f := range group.findings {
				line := "-"
				if f.Line > 0 {
					line = fmt.Sprintf("%d", f.Line)
				}
				fmt.Fprintf(&b, "| %s | %s | %s | %s |\n",
					line, severityBadge(f.Severity), f.Role, f.Summary)
			}
			b.WriteString("\n")

			// Details for warnings and criticals.
			for _, f := range group.findings {
				if f.Severity == "info" {
					continue
				}
				fmt.Fprintf(&b, "**%s** (line %d, %s) — %s\n\n",
					severityBadge(f.Severity), f.Line, f.Role, f.Summary)
				b.WriteString(f.Detail)
				b.WriteString("\n\n")
			}
		}
	}

	// Suggestions summary.
	if len(d.Result.Suggestions) > 0 {
		fmt.Fprintf(&b, "---\n\n*%d inline suggestions available. Use `--comment` to post them to the PR.*\n\n", len(d.Result.Suggestions))
	}

	b.WriteString("---\n\n*Generated by [Shinobi](https://github.com/arinorr/shinobi)*\n")

	return b.String()
}

// HTML converts the markdown report to HTML with basic styling.
func HTML(d *Data) (string, error) {
	md := Markdown(d)

	var buf bytes.Buffer
	if err := goldmark.Convert([]byte(md), &buf); err != nil {
		return "", fmt.Errorf("markdown to HTML conversion failed: %w", err)
	}

	var out strings.Builder
	out.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Shinobi Review: PR #` + d.PR.Number + `</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; line-height: 1.6; color: #24292e; }
  table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
  th, td { border: 1px solid #d0d7de; padding: 6px 13px; text-align: left; }
  th { background: #f6f8fa; font-weight: 600; }
  tr:nth-child(even) { background: #f6f8fa; }
  code { background: #f6f8fa; padding: 0.2em 0.4em; border-radius: 3px; font-size: 85%; }
  pre { background: #f6f8fa; padding: 1rem; border-radius: 6px; overflow-x: auto; }
  hr { border: none; border-top: 1px solid #d0d7de; margin: 2rem 0; }
  h1 { border-bottom: 1px solid #d0d7de; padding-bottom: 0.3em; }
  h2 { border-bottom: 1px solid #d0d7de; padding-bottom: 0.3em; }
  h3 { margin-top: 1.5rem; }
</style>
</head>
<body>
`)
	out.WriteString(buf.String())
	out.WriteString("\n</body>\n</html>\n")

	return out.String(), nil
}

// JSON outputs the review result as structured JSON.
func JSON(d *Data) (string, error) {
	output := struct {
		PR          prSummary        `json:"pr"`
		Summary     string           `json:"summary"`
		Findings    []agents.Finding `json:"findings"`
		Suggestions []suggestionJSON `json:"suggestions"`
		Roles       []string         `json:"roles"`
		Duration    string           `json:"duration,omitempty"`
	}{
		PR: prSummary{
			Number: d.PR.Number,
			Title:  d.PR.Title,
			Files:  len(d.PR.Files),
		},
		Summary:     d.Result.Summary,
		Findings:    d.Result.Findings,
		Suggestions: toSuggestionJSON(d.Result.Suggestions),
		Roles:       d.Roles,
		Duration:    d.Duration,
	}

	data, err := json.MarshalIndent(output, "", "  ")
	if err != nil {
		return "", err
	}
	return string(data), nil
}

type prSummary struct {
	Number string `json:"number"`
	Title  string `json:"title"`
	Files  int    `json:"files"`
}

type suggestionJSON struct {
	File string `json:"file"`
	Line int    `json:"line"`
	Body string `json:"body"`
	Role string `json:"role"`
}

func toSuggestionJSON(suggestions []gh.Suggestion) []suggestionJSON {
	out := make([]suggestionJSON, len(suggestions))
	for i, s := range suggestions {
		out[i] = suggestionJSON{File: s.File, Line: s.Line, Body: s.Body, Role: s.Role}
	}
	return out
}

type fileGroup struct {
	file     string
	findings []agents.Finding
}

func groupByFile(findings []agents.Finding) []fileGroup {
	byFile := make(map[string][]agents.Finding)
	for _, f := range findings {
		file := f.File
		if file == "" {
			file = "(general)"
		}
		byFile[file] = append(byFile[file], f)
	}

	groups := make([]fileGroup, 0, len(byFile))
	for file, fs := range byFile {
		// Sort by severity (critical > warning > info), then by line.
		sort.Slice(fs, func(i, j int) bool {
			si, sj := severityOrder(fs[i].Severity), severityOrder(fs[j].Severity)
			if si != sj {
				return si < sj
			}
			return fs[i].Line < fs[j].Line
		})
		groups = append(groups, fileGroup{file: file, findings: fs})
	}

	sort.Slice(groups, func(i, j int) bool {
		return groups[i].file < groups[j].file
	})

	return groups
}

const (
	severityCritical = "critical"
	severityWarning  = "warning"
)

func severityOrder(s string) int {
	switch s {
	case severityCritical:
		return 0
	case severityWarning:
		return 1
	default:
		return 2
	}
}

func severityBadge(s string) string {
	switch s {
	case severityCritical:
		return "🔴 critical"
	case severityWarning:
		return "🟡 warning"
	default:
		return "🔵 info"
	}
}
