// Package report generates review reports in markdown, HTML, and JSON formats.
package report

import (
	"bytes"
	"encoding/json"
	"fmt"
	"html"
	"sort"
	"strings"

	"github.com/microcosm-cc/bluemonday"
	"github.com/yuin/goldmark"

	"github.com/arinorr/prism/internal/agents"
	"github.com/arinorr/prism/internal/gh"
)

// Data holds everything needed to generate a report.
type Data struct {
	PR       *gh.PR
	Result   *agents.ReviewResult
	Roles    []string
	Duration string
}

// Markdown generates a markdown report from the review data.
func Markdown(d *Data) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Prism Review: PR #%s\n\n", d.PR.Number)
	fmt.Fprintf(&b, "**%s**\n\n", d.PR.Title)
	fmt.Fprintf(&b, "Files changed: %d | Agents: %s", len(d.PR.Files), strings.Join(d.Roles, ", "))
	if d.Duration != "" {
		fmt.Fprintf(&b, " | Duration: %s", d.Duration)
	}
	b.WriteString("\n\n---\n\n")

	// Failed agents notice.
	if len(d.Result.FailedAgents) > 0 {
		fmt.Fprintf(&b, "> ⚠️ **%d agent(s) failed:** %s\n\n",
			len(d.Result.FailedAgents), strings.Join(d.Result.FailedAgents, ", "))
	}

	// Summary from synthesis.
	b.WriteString("## Summary\n\n")
	b.WriteString(d.Result.Summary)
	b.WriteString("\n\n")

	// Findings grouped by file — use deduped if available.
	if len(d.Result.DedupedFindings) > 0 {
		b.WriteString("---\n\n## Findings by File\n\n")
		grouped := groupDedupedByFile(d.Result.DedupedFindings)
		for _, group := range grouped {
			fmt.Fprintf(&b, "### `%s`\n\n", group.file)
			b.WriteString("| Line | Severity | Votes | Summary |\n")
			b.WriteString("|------|----------|-------|---------|\n")
			for i := range group.findings {
				f := &group.findings[i]
				line := "-"
				if f.Line > 0 {
					line = fmt.Sprintf("%d", f.Line)
				}
				votes := fmt.Sprintf("%d/%d", f.VoteCount, f.TotalAgents)
				fmt.Fprintf(&b, "| %s | %s | %s | %s |\n",
					line, severityBadge(f.Severity), votes, f.Summary)
			}
			b.WriteString("\n")

			// Details for warnings and criticals.
			for i := range group.findings {
				f := &group.findings[i]
				if f.Severity == severityInfo {
					continue
				}
				voters := strings.Join(f.Voters, ", ")
				if f.Line > 0 {
					fmt.Fprintf(&b, "**%s** (line %d, %d/%d agents: %s) — %s\n\n",
						severityBadge(f.Severity), f.Line, f.VoteCount, f.TotalAgents, voters, f.Summary)
				} else {
					fmt.Fprintf(&b, "**%s** (%d/%d agents: %s) — %s\n\n",
						severityBadge(f.Severity), f.VoteCount, f.TotalAgents, voters, f.Summary)
				}
				b.WriteString(f.Detail)
				b.WriteString("\n\n")
			}
		}
	} else if len(d.Result.Findings) > 0 {
		b.WriteString("---\n\n## Findings by File\n\n")
		grouped := groupByFile(d.Result.Findings)
		for _, group := range grouped {
			fmt.Fprintf(&b, "### `%s`\n\n", group.file)
			b.WriteString("| Line | Severity | Agent | Summary |\n")
			b.WriteString("|------|----------|-------|---------|\n")
			for _, f := range group.findings {
				line := "-"
				if f.Line > 0 {
					line = fmt.Sprintf("%d", f.Line)
				}
				fmt.Fprintf(&b, "| %s | %s | %s | %s |\n",
					line, severityBadge(f.Severity), f.Role, f.Summary)
			}
			b.WriteString("\n")

			// Details for warnings and criticals.
			for _, f := range group.findings {
				if f.Severity == severityInfo {
					continue
				}
				if f.Line > 0 {
					fmt.Fprintf(&b, "**%s** (line %d, %s) — %s\n\n",
						severityBadge(f.Severity), f.Line, f.Role, f.Summary)
				} else {
					fmt.Fprintf(&b, "**%s** (%s) — %s\n\n",
						severityBadge(f.Severity), f.Role, f.Summary)
				}
				b.WriteString(f.Detail)
				b.WriteString("\n\n")
			}
		}
	}

	// Suggestions summary.
	if len(d.Result.Suggestions) > 0 {
		fmt.Fprintf(&b, "---\n\n*%d inline suggestions available. Use `--comment` to post them to the PR.*\n\n", len(d.Result.Suggestions))
	}

	b.WriteString("---\n\n*Generated by [Prism](https://github.com/arinorr/prism)*\n")

	return b.String()
}

// HTML generates a styled HTML report directly from the review data.
func HTML(d *Data) (string, error) {
	// Convert the synthesis summary from markdown to HTML, then sanitize
	// to strip any <script>, <iframe>, event handlers, etc. that could
	// be injected via prompt injection of the LLM output.
	var rawHTML bytes.Buffer
	if err := goldmark.Convert([]byte(d.Result.Summary), &rawHTML); err != nil {
		return "", fmt.Errorf("markdown to HTML conversion failed: %w", err)
	}
	sanitizer := bluemonday.UGCPolicy()
	summaryHTML := sanitizer.Sanitize(rawHTML.String())

	// Count severities for the stats bar.
	var critCount, warnCount, infoCount int
	for _, f := range d.Result.Findings {
		switch f.Severity {
		case severityCritical:
			critCount++
		case severityWarning:
			warnCount++
		default:
			infoCount++
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Prism Review: PR #%s</title>
<style>
:root { --bg: #ffffff; --fg: #1f2328; --muted: #656d76; --border: #d0d7de; --surface: #f6f8fa; --red: #cf222e; --red-bg: #ffebe9; --yellow: #9a6700; --yellow-bg: #fff8c5; --blue: #0969da; --blue-bg: #ddf4ff; --green: #1a7f37; --green-bg: #dafbe1; }
* { box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; max-width: 960px; margin: 0 auto; padding: 2rem 1.5rem; line-height: 1.6; color: var(--fg); background: var(--bg); }
h1 { font-size: 1.5rem; margin: 0; }
h2 { font-size: 1.25rem; margin: 2rem 0 1rem; padding-bottom: 0.4em; border-bottom: 1px solid var(--border); }
.header { border-bottom: 2px solid var(--border); padding-bottom: 1rem; margin-bottom: 1.5rem; }
.header .pr-title { color: var(--muted); font-size: 1rem; margin: 0.25rem 0 0.75rem; }
.meta { display: flex; gap: 1.5rem; flex-wrap: wrap; font-size: 0.85rem; color: var(--muted); }
.stats { display: flex; gap: 0.75rem; margin: 1.5rem 0; }
.stat { display: flex; align-items: center; gap: 0.4rem; padding: 0.5rem 1rem; border-radius: 6px; font-weight: 600; font-size: 0.9rem; }
.stat-critical { background: var(--red-bg); color: var(--red); }
.stat-warning { background: var(--yellow-bg); color: var(--yellow); }
.stat-info { background: var(--blue-bg); color: var(--blue); }
.stat-suggestions { background: var(--green-bg); color: var(--green); }
.stat .num { font-size: 1.25rem; }
.summary { background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 1rem 1.5rem; margin: 1.5rem 0; }
.summary h1, .summary h2, .summary h3 { font-size: 1.1rem; border: none; margin: 1rem 0 0.5rem; padding: 0; }
.summary p { margin: 0.5rem 0; }
.summary ul, .summary ol { padding-left: 1.5rem; }
.summary table { border-collapse: collapse; width: 100%%; margin: 0.75rem 0; font-size: 0.85rem; }
.summary th, .summary td { border: 1px solid var(--border); padding: 4px 10px; text-align: left; }
.summary th { background: var(--bg); }
.summary pre { background: var(--bg); border: 1px solid var(--border); padding: 0.75rem; border-radius: 4px; overflow-x: auto; font-size: 0.8rem; }
.summary code { background: var(--bg); padding: 0.15em 0.35em; border-radius: 3px; font-size: 0.85em; }
.summary hr { border: none; border-top: 1px solid var(--border); margin: 1.25rem 0; }
.file-group { border: 1px solid var(--border); border-radius: 8px; margin: 1rem 0; overflow: hidden; }
.file-header { background: var(--surface); padding: 0.6rem 1rem; font-weight: 600; font-family: SFMono-Regular, Consolas, monospace; font-size: 0.9rem; border-bottom: 1px solid var(--border); cursor: pointer; display: flex; justify-content: space-between; align-items: center; }
.file-header:hover { background: #eaeef2; }
.file-header .counts { display: flex; gap: 0.5rem; font-size: 0.75rem; font-weight: normal; font-family: -apple-system, sans-serif; }
.file-header .counts span { padding: 0.15rem 0.5rem; border-radius: 10px; }
.badge-critical { background: var(--red-bg); color: var(--red); }
.badge-warning { background: var(--yellow-bg); color: var(--yellow); }
.badge-info { background: var(--blue-bg); color: var(--blue); }
.finding { padding: 0.75rem 1rem; border-bottom: 1px solid var(--border); }
.finding:last-child { border-bottom: none; }
.finding-header { display: flex; align-items: center; gap: 0.5rem; margin-bottom: 0.25rem; }
.finding-header .severity { font-size: 0.75rem; font-weight: 600; padding: 0.15rem 0.5rem; border-radius: 10px; text-transform: uppercase; letter-spacing: 0.03em; }
.finding-header .line { font-size: 0.8rem; color: var(--muted); font-family: SFMono-Regular, Consolas, monospace; }
.finding-header .role { font-size: 0.8rem; color: var(--muted); }
.finding-summary { font-weight: 600; margin-bottom: 0.25rem; }
.finding-detail { font-size: 0.9rem; color: var(--muted); line-height: 1.5; }
.finding-detail code { background: var(--surface); padding: 0.1em 0.3em; border-radius: 3px; font-size: 0.85em; }
.footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--border); font-size: 0.8rem; color: var(--muted); text-align: center; }
.footer a { color: var(--blue); text-decoration: none; }
</style>
</head>
<body>

<div class="header">
  <h1>Prism Review: PR #%s</h1>
  <div class="pr-title">%s</div>
  <div class="meta">
    <span>%d files changed</span>
    <span>%d agents</span>
    <span>%d findings</span>
`, esc(d.PR.Number), esc(d.PR.Number), esc(d.PR.Title), len(d.PR.Files), len(d.Roles), len(d.Result.Findings))

	if d.Duration != "" {
		fmt.Fprintf(&b, "    <span>%s</span>\n", d.Duration)
	}
	b.WriteString("  </div>\n</div>\n\n")

	// Stats bar.
	b.WriteString("<div class=\"stats\">\n")
	fmt.Fprintf(&b, "  <div class=\"stat stat-critical\"><span class=\"num\">%d</span> critical</div>\n", critCount)
	fmt.Fprintf(&b, "  <div class=\"stat stat-warning\"><span class=\"num\">%d</span> warning</div>\n", warnCount)
	fmt.Fprintf(&b, "  <div class=\"stat stat-info\"><span class=\"num\">%d</span> info</div>\n", infoCount)
	fmt.Fprintf(&b, "  <div class=\"stat stat-suggestions\"><span class=\"num\">%d</span> suggestions</div>\n", len(d.Result.Suggestions))
	b.WriteString("</div>\n\n")

	// Synthesis summary.
	// Failed agents notice.
	if len(d.Result.FailedAgents) > 0 {
		fmt.Fprintf(&b, "<div style=\"background:var(--yellow-bg);color:var(--yellow);padding:0.75rem 1rem;border-radius:6px;margin-bottom:1rem\">⚠️ <strong>%d agent(s) failed:</strong> %s</div>\n",
			len(d.Result.FailedAgents), esc(strings.Join(d.Result.FailedAgents, ", ")))
	}

	b.WriteString("<h2>Summary</h2>\n")
	b.WriteString("<div class=\"summary\">\n")
	b.WriteString(summaryHTML)
	b.WriteString("</div>\n\n")

	// Findings grouped by file.
	if len(d.Result.Findings) > 0 {
		b.WriteString("<h2>Findings by File</h2>\n\n")
		grouped := groupByFile(d.Result.Findings)
		for _, group := range grouped {
			// Count per-file severities.
			var fc, fw, fi int
			for _, f := range group.findings {
				switch f.Severity {
				case severityCritical:
					fc++
				case severityWarning:
					fw++
				default:
					fi++
				}
			}

			b.WriteString("<div class=\"file-group\">\n")
			fmt.Fprintf(&b, "  <div class=\"file-header\"><span>%s</span><div class=\"counts\">", esc(group.file))
			if fc > 0 {
				fmt.Fprintf(&b, "<span class=\"badge-critical\">%d critical</span>", fc)
			}
			if fw > 0 {
				fmt.Fprintf(&b, "<span class=\"badge-warning\">%d warning</span>", fw)
			}
			if fi > 0 {
				fmt.Fprintf(&b, "<span class=\"badge-info\">%d info</span>", fi)
			}
			b.WriteString("</div></div>\n")

			for _, f := range group.findings {
				severityClass := "badge-info"
				switch f.Severity {
				case severityCritical:
					severityClass = "badge-critical"
				case severityWarning:
					severityClass = "badge-warning"
				}

				b.WriteString("  <div class=\"finding\">\n")
				b.WriteString("    <div class=\"finding-header\">\n")
				fmt.Fprintf(&b, "      <span class=\"severity %s\">%s</span>\n", severityClass, esc(f.Severity))
				if f.Line > 0 {
					fmt.Fprintf(&b, "      <span class=\"line\">line %d</span>\n", f.Line)
				}
				fmt.Fprintf(&b, "      <span class=\"role\">%s</span>\n", esc(f.Role))
				b.WriteString("    </div>\n")
				fmt.Fprintf(&b, "    <div class=\"finding-summary\">%s</div>\n", esc(f.Summary))
				if f.Detail != "" {
					fmt.Fprintf(&b, "    <div class=\"finding-detail\">%s</div>\n", esc(f.Detail))
				}
				b.WriteString("  </div>\n")
			}
			b.WriteString("</div>\n\n")
		}
	}

	// Footer.
	b.WriteString("<div class=\"footer\">Generated by <a href=\"https://github.com/arinorr/prism\">Prism</a></div>\n")
	b.WriteString("\n</body>\n</html>\n")

	return b.String(), nil
}

// JSON outputs the review result as structured JSON.
func JSON(d *Data) (string, error) {
	// Ensure slices serialize as [] not null.
	findings := d.Result.Findings
	if findings == nil {
		findings = []agents.Finding{}
	}
	suggestions := toSuggestionJSON(d.Result.Suggestions)
	if suggestions == nil {
		suggestions = []suggestionJSON{}
	}
	roles := d.Roles
	if roles == nil {
		roles = []string{}
	}

	dedupedFindings := d.Result.DedupedFindings
	if dedupedFindings == nil {
		dedupedFindings = []agents.DedupedFinding{}
	}
	failedAgents := d.Result.FailedAgents
	if failedAgents == nil {
		failedAgents = []string{}
	}

	output := struct {
		PR              prSummary               `json:"pr"`
		Summary         string                  `json:"summary"`
		Findings        []agents.Finding        `json:"findings"`
		DedupedFindings []agents.DedupedFinding `json:"deduped_findings"`
		Suggestions     []suggestionJSON        `json:"suggestions"`
		Roles           []string                `json:"roles"`
		FailedAgents    []string                `json:"failed_agents"`
		Duration        string                  `json:"duration,omitempty"`
	}{
		PR: prSummary{
			Number: d.PR.Number,
			Title:  d.PR.Title,
			Files:  len(d.PR.Files),
		},
		Summary:         d.Result.Summary,
		Findings:        findings,
		DedupedFindings: dedupedFindings,
		Suggestions:     suggestions,
		Roles:           roles,
		FailedAgents:    failedAgents,
		Duration:        d.Duration,
	}

	data, err := json.MarshalIndent(output, "", "  ")
	if err != nil {
		return "", err
	}
	return string(data), nil
}

type prSummary struct {
	Number string `json:"number"`
	Title  string `json:"title"`
	Files  int    `json:"files"`
}

type suggestionJSON struct {
	File string `json:"file"`
	Line int    `json:"line"`
	Body string `json:"body"`
	Role string `json:"role"`
}

func toSuggestionJSON(suggestions []gh.Suggestion) []suggestionJSON {
	out := make([]suggestionJSON, len(suggestions))
	for i, s := range suggestions {
		out[i] = suggestionJSON{File: s.File, Line: s.Line, Body: s.Body, Role: s.Role}
	}
	return out
}

const generalFile = "(general)"

type fileGroup struct {
	file     string
	findings []agents.Finding
}

func groupByFile(findings []agents.Finding) []fileGroup {
	byFile := make(map[string][]agents.Finding)
	for _, f := range findings {
		file := f.File
		if file == "" {
			file = generalFile
		}
		byFile[file] = append(byFile[file], f)
	}

	groups := make([]fileGroup, 0, len(byFile))
	for file, fs := range byFile {
		// Sort by severity (critical > warning > info), then by line.
		sort.Slice(fs, func(i, j int) bool {
			si, sj := severityOrder(fs[i].Severity), severityOrder(fs[j].Severity)
			if si != sj {
				return si < sj
			}
			return fs[i].Line < fs[j].Line
		})
		groups = append(groups, fileGroup{file: file, findings: fs})
	}

	sort.Slice(groups, func(i, j int) bool {
		return groups[i].file < groups[j].file
	})

	return groups
}

type dedupedFileGroup struct {
	file     string
	findings []agents.DedupedFinding
}

func groupDedupedByFile(findings []agents.DedupedFinding) []dedupedFileGroup {
	byFile := make(map[string][]agents.DedupedFinding)
	for i := range findings {
		file := findings[i].File
		if file == "" {
			file = generalFile
		}
		byFile[file] = append(byFile[file], findings[i])
	}

	groups := make([]dedupedFileGroup, 0, len(byFile))
	for file, fs := range byFile {
		sort.Slice(fs, func(i, j int) bool {
			// Vote count desc first, then severity, then line.
			if fs[i].VoteCount != fs[j].VoteCount {
				return fs[i].VoteCount > fs[j].VoteCount
			}
			si, sj := severityOrder(fs[i].Severity), severityOrder(fs[j].Severity)
			if si != sj {
				return si < sj
			}
			return fs[i].Line < fs[j].Line
		})
		groups = append(groups, dedupedFileGroup{file: file, findings: fs})
	}

	sort.Slice(groups, func(i, j int) bool {
		return groups[i].file < groups[j].file
	})

	return groups
}

const (
	severityCritical = "critical"
	severityWarning  = "warning"
	severityInfo     = "info"
)

func severityOrder(s string) int {
	switch s {
	case severityCritical:
		return 0
	case severityWarning:
		return 1
	default:
		return 2
	}
}

// esc escapes a string for safe HTML output.
func esc(s string) string {
	return html.EscapeString(s)
}

func severityBadge(s string) string {
	switch s {
	case severityCritical:
		return "🔴 critical"
	case severityWarning:
		return "🟡 warning"
	default:
		return "🔵 info"
	}
}
