package diff

import (
	"strings"
	"testing"
)

const sampleDiff = `diff --git a/main.go b/main.go
index abc1234..def5678 100644
--- a/main.go
+++ b/main.go
@@ -10,6 +10,8 @@ func main() {
 	fmt.Println("hello")
 	fmt.Println("context1")
 	fmt.Println("context2")
+	fmt.Println("added line")
 	fmt.Println("context3")
 	fmt.Println("context4")
 	fmt.Println("context5")
`

const lockFileDiff = `diff --git a/package-lock.json b/package-lock.json
index 1234567..abcdefg 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -1,5 +1,5 @@
 {
-  "version": "1.0.0",
+  "version": "1.0.1",
   "dependencies": {
     "lodash": "4.17.21"
   }
`

const binaryDiff = `diff --git a/image.png b/image.png
Binary files a/image.png and b/image.png differ
`

const generatedDiff = `diff --git a/proto/service.pb.go b/proto/service.pb.go
index 111..222 100644
--- a/proto/service.pb.go
+++ b/proto/service.pb.go
@@ -1,3 +1,4 @@
 // Code generated by protoc-gen-go. DO NOT EDIT.
+// Added generated line
 package proto
`

const vendorDiff = `diff --git a/vendor/lib/util.go b/vendor/lib/util.go
index aaa..bbb 100644
--- a/vendor/lib/util.go
+++ b/vendor/lib/util.go
@@ -1,3 +1,4 @@
 package lib
+func Added() {}
`

func TestCompress_StripLockFiles(t *testing.T) {
	t.Parallel()
	input := sampleDiff + lockFileDiff
	result, summary := Compress(input, DefaultOptions())

	if strings.Contains(result, "package-lock.json") {
		t.Error("lock file should be stripped")
	}
	if !strings.Contains(result, "main.go") {
		t.Error("code file should be preserved")
	}
	if len(summary.FilesRemoved) != 1 || summary.FilesRemoved[0] != "package-lock.json" {
		t.Errorf("expected 1 removed file, got %v", summary.FilesRemoved)
	}
}

func TestCompress_StripGenerated(t *testing.T) {
	t.Parallel()
	input := sampleDiff + generatedDiff
	result, summary := Compress(input, DefaultOptions())

	if strings.Contains(result, "service.pb.go") {
		t.Error("generated file should be stripped")
	}
	if len(summary.FilesRemoved) != 1 {
		t.Errorf("expected 1 removed file, got %d", len(summary.FilesRemoved))
	}
}

func TestCompress_StripBinary(t *testing.T) {
	t.Parallel()
	input := sampleDiff + binaryDiff
	result, summary := Compress(input, DefaultOptions())

	if strings.Contains(result, "Binary files") {
		t.Error("binary diff should be stripped")
	}
	if len(summary.FilesRemoved) != 1 || summary.FilesRemoved[0] != "image.png" {
		t.Errorf("expected image.png removed, got %v", summary.FilesRemoved)
	}
}

func TestCompress_StripVendor(t *testing.T) {
	t.Parallel()
	input := sampleDiff + vendorDiff
	result, summary := Compress(input, DefaultOptions())

	if strings.Contains(result, "vendor/lib") {
		t.Error("vendor file should be stripped")
	}
	if len(summary.FilesRemoved) != 1 {
		t.Errorf("expected 1 removed file, got %d", len(summary.FilesRemoved))
	}
}

func TestCompress_PreservesCodeChanges(t *testing.T) {
	t.Parallel()
	result, _ := Compress(sampleDiff, DefaultOptions())

	if !strings.Contains(result, "added line") {
		t.Error("added lines should be preserved")
	}
	if !strings.Contains(result, "main.go") {
		t.Error("file header should be preserved")
	}
	if !strings.Contains(result, "@@") {
		t.Error("hunk markers should be preserved")
	}
}

func TestCompress_ReduceContext(t *testing.T) {
	t.Parallel()
	opts := DefaultOptions()
	opts.ContextLines = 1

	result, summary := Compress(sampleDiff, opts)

	if !summary.ContextReduced {
		t.Error("expected ContextReduced=true")
	}
	// With 1 context line, we should keep 1 line before and 1 after the change.
	if !strings.Contains(result, "added line") {
		t.Error("change lines must be preserved")
	}
	// context5 is 3 lines after the change — should be omitted with 1 context line.
	if strings.Contains(result, "context5") {
		t.Error("far context lines should be stripped with ContextLines=1")
	}
}

func TestCompress_StripAllContext(t *testing.T) {
	t.Parallel()
	opts := DefaultOptions()
	opts.ContextLines = 0

	result, _ := Compress(sampleDiff, opts)

	if !strings.Contains(result, "added line") {
		t.Error("change lines must be preserved")
	}
	// All context lines should be gone.
	if strings.Contains(result, "context1") {
		t.Error("all context lines should be stripped with ContextLines=0")
	}
}

func TestCompress_KeepAllContext(t *testing.T) {
	t.Parallel()
	opts := DefaultOptions()
	opts.ContextLines = -1

	result, summary := Compress(sampleDiff, opts)

	if summary.ContextReduced {
		t.Error("expected ContextReduced=false with ContextLines=-1")
	}
	if !strings.Contains(result, "context1") {
		t.Error("all context should be preserved with ContextLines=-1")
	}
	if !strings.Contains(result, "context5") {
		t.Error("all context should be preserved with ContextLines=-1")
	}
}

func TestCompress_MixedDiff(t *testing.T) {
	t.Parallel()
	input := sampleDiff + lockFileDiff + binaryDiff + generatedDiff + vendorDiff
	result, summary := Compress(input, DefaultOptions())

	if !strings.Contains(result, "main.go") {
		t.Error("code file should survive")
	}
	if strings.Contains(result, "package-lock") {
		t.Error("lock file should be removed")
	}
	if strings.Contains(result, "Binary files") {
		t.Error("binary should be removed")
	}
	if strings.Contains(result, "service.pb.go") {
		t.Error("generated should be removed")
	}
	if strings.Contains(result, "vendor/") {
		t.Error("vendor should be removed")
	}
	if len(summary.FilesRemoved) != 4 {
		t.Errorf("expected 4 removed files, got %d: %v", len(summary.FilesRemoved), summary.FilesRemoved)
	}
}

func TestCompress_Summary(t *testing.T) {
	t.Parallel()
	input := sampleDiff + lockFileDiff
	_, summary := Compress(input, DefaultOptions())

	if summary.OriginalBytes != len(input) {
		t.Errorf("OriginalBytes: expected %d, got %d", len(input), summary.OriginalBytes)
	}
	if summary.CompressedBytes >= summary.OriginalBytes {
		t.Errorf("compressed should be smaller: %d >= %d", summary.CompressedBytes, summary.OriginalBytes)
	}
}

func TestCompress_NoCompression(t *testing.T) {
	t.Parallel()
	opts := NoCompression()
	result, summary := Compress(sampleDiff, opts)

	if result != sampleDiff {
		t.Error("NoCompression should return input unchanged")
	}
	if len(summary.FilesRemoved) != 0 {
		t.Errorf("expected no files removed, got %v", summary.FilesRemoved)
	}
	if summary.ContextReduced {
		t.Error("expected no context reduction")
	}
}

func TestCompress_CustomPatterns(t *testing.T) {
	t.Parallel()
	customDiff := `diff --git a/custom/output.go b/custom/output.go
index abc..def 100644
--- a/custom/output.go
+++ b/custom/output.go
@@ -1,3 +1,4 @@
 package custom
+func New() {}
`
	input := sampleDiff + customDiff
	opts := DefaultOptions()
	opts.ExtraPatterns = []string{"custom/*"}

	result, summary := Compress(input, opts)

	if strings.Contains(result, "custom/output.go") {
		t.Error("custom pattern file should be stripped")
	}
	if len(summary.FilesRemoved) != 1 {
		t.Errorf("expected 1 removed, got %d", len(summary.FilesRemoved))
	}
}

func TestCompress_EmptyDiff(t *testing.T) {
	t.Parallel()
	result, summary := Compress("", DefaultOptions())
	if result != "" {
		t.Error("empty diff should return empty string")
	}
	if summary.OriginalBytes != 0 {
		t.Errorf("expected 0 original bytes, got %d", summary.OriginalBytes)
	}
}

func TestExtractFilePath(t *testing.T) {
	t.Parallel()
	tests := []struct {
		input string
		want  string
	}{
		{"diff --git a/foo.go b/foo.go\n", "foo.go"},
		{"diff --git a/internal/pkg/bar.go b/internal/pkg/bar.go\n", "internal/pkg/bar.go"},
		{"not a diff\n", ""},
	}
	for _, tt := range tests {
		got := extractFilePath(tt.input)
		if got != tt.want {
			t.Errorf("extractFilePath(%q) = %q, want %q", tt.input, got, tt.want)
		}
	}
}

func TestIsLockFile(t *testing.T) {
	t.Parallel()
	for _, name := range []string{"package-lock.json", "yarn.lock", "go.sum", "Cargo.lock"} {
		if !isLockFile(name) {
			t.Errorf("expected %q to be a lock file", name)
		}
	}
	if isLockFile("main.go") {
		t.Error("main.go should not be a lock file")
	}
}

func TestIsBinaryDiff(t *testing.T) {
	t.Parallel()
	if !isBinaryDiff(binaryDiff) {
		t.Error("expected binary diff to be detected")
	}
	if isBinaryDiff(sampleDiff) {
		t.Error("code diff should not be detected as binary")
	}
}
